trigger:
- master

jobs: 
  - job: 'InstallDeps'
    pool:
      vmImage: 'Ubuntu-16.04'
    strategy:
      matrix:
        Python37:
          python.version: '3.7'
          TOXENV: py37
    steps:
      - script: pip install --upgrade pip
        displayName: Upgrade pip
      - script: pip install c7n
        displayName: Install custodian

  - job: 'Validate'
    pool:
      vmImage: 'Ubuntu-16.04'
    strategy:
      matrix:
        Python37:
          python.version: '3.7'
          TOXENV: py37
    steps:
      - checkout: self
      - script: custodian validate policy.yml
        displayName: Validate policy file