trigger:
- master

jobs: 
  - job: 'Validate'
    pool:
      vmImage: 'Ubuntu-16.04'
    strategy:
      matrix:
        Python37:
          python.version: '3.7'
          TOXENV: py37
    steps:
      - checkout: self
      - task: UsePythonVersion@0
        displayName: "Set Python Version"
        inputs:
          versionSpec: '$(python.version)'
          architecture: 'x64'
      - script: pip install --upgrade pip
        displayName: Upgrade pip
      - script: pip install c7n
        displayName: Install custodian
      - script: custodian validate policy.yml
        displayName: Validate policy file